### ISSUE TITLE
Unable to resolve module Dimensions

### ISSUE THREAD

**Issue by jsntghf** [superdami/react-native-custom-navigation#7]
I'm getting the following:
![simulator screen shot 2015 12 22 11 28 27](https://cloud.githubusercontent.com/assets/182790/11947240/22e8e4c2-a89f-11e5-9204-4d787294a386.png)

react-native 0.15.0

**Comment by Creemli** [comment]
I also saw this error， and if I move the folder outside the /node_modules , it worked.

**Comment by ericraio** [comment]
@SuperDami please update npm, the github repo resolved the issue for me but on npm, it seems to be stale.

**Comment by SuperDami** [comment]
Updated to 0.2.2
